### ISSUE TITLE
how can i get the insightface and VGGFace2-resnet pretrianed models?

### ISSUE THREAD

**Issue by UCC-team** [wvinzh/WutongFace#1]
how can i get the insightface and VGGFace2-resnet pretrianed models?The file seems to be deleted. thanks!

**Comment by UCC-team** [comment]
![image](https://user-images.githubusercontent.com/35629974/56482583-873afb00-64f7-11e9-9ab4-29d1b4d62a1d.png)

**Comment by wvinzh** [comment]
2

> how can i get the insightface and VGGFace2-resnet pretrianed models?The file seems to be deleted. thanks!

@UCC-team Sorry,I moved it to another place, you can download now since I have updated the urls.
